In [290]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from ast import literal_eval
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [291]:
data=pd.read_excel('아이템기반최종데이터.xlsx')
data.head()

Unnamed: 0                              상품명    색깔   카테고리            RGB  \
0           0    [DAYONE LABEL]렌프 자켓원피스(벨트set)    블랙  미니원피스        0, 0, 0   
1           1             [DAYONE LABEL]로티 숏팬츠    연청    반바지  190, 210, 237   
2           2            [DAYONE LABEL]슬로 보트넥티   옐로우    티셔츠  245, 230, 160   
3           3         [DAYONE LABEL]워프 스퀘어롱원피스  피치핑크   롱원피스  220, 174, 166   
4           4  [DAYONE LABEL]케이즈 하이스키니진 (히든밴딩)    블루   스키니    85, 100, 113   

  패턴재질   모양      계절  평균평점    스타일  종합점수  
0   무지   단추   겨울      0.0   모던시크   0.0  
1   무지   포켓  봄 여름     0.0  심플베이직   0.0  
2   무지  보트넥  봄 가을     0.0     청순   0.0  
3   데님   크롭   여름      0.0     청순   0.0  
4   무지   슬림   겨울      0.0    캐주얼   0.0

In [292]:
data.columns

Index(['Unnamed: 0', '상품명', '색깔', '카테고리', 'RGB', '패턴재질', '모양', '계절', '평균평점',
       '스타일', '종합점수'],
      dtype='object')

In [293]:
data=data[['상품명','카테고리','패턴재질','모양','계절','종합점수','스타일']]
data.head()

상품명   카테고리 패턴재질   모양      계절  종합점수    스타일
0    [DAYONE LABEL]렌프 자켓원피스(벨트set)  미니원피스   무지   단추   겨울      0.0   모던시크
1             [DAYONE LABEL]로티 숏팬츠    반바지   무지   포켓  봄 여름     0.0  심플베이직
2            [DAYONE LABEL]슬로 보트넥티    티셔츠   무지  보트넥  봄 가을     0.0     청순
3         [DAYONE LABEL]워프 스퀘어롱원피스   롱원피스   데님   크롭   여름      0.0     청순
4  [DAYONE LABEL]케이즈 하이스키니진 (히든밴딩)   스키니    무지   슬림   겨울      0.0    캐주얼

In [294]:
df=data.drop_duplicates(['상품명'])
df.shape

(1845, 7)

In [295]:
df.head()

상품명   카테고리 패턴재질   모양      계절  종합점수    스타일
0    [DAYONE LABEL]렌프 자켓원피스(벨트set)  미니원피스   무지   단추   겨울      0.0   모던시크
1             [DAYONE LABEL]로티 숏팬츠    반바지   무지   포켓  봄 여름     0.0  심플베이직
2            [DAYONE LABEL]슬로 보트넥티    티셔츠   무지  보트넥  봄 가을     0.0     청순
3         [DAYONE LABEL]워프 스퀘어롱원피스   롱원피스   데님   크롭   여름      0.0     청순
4  [DAYONE LABEL]케이즈 하이스키니진 (히든밴딩)   스키니    무지   슬림   겨울      0.0    캐주얼

In [296]:
df.shape

(1845, 7)

In [297]:
df.index

Int64Index([   0,    1,    2,    3,    4,    6,    8,    9,   10,   12,
            ...
            3488, 3490, 3492, 3493, 3495, 3498, 3499, 3500, 3501, 3502],
           dtype='int64', length=1845)

In [298]:
df.index=pd.Series(range(1845),index=df.index)
print(df.index)

Int64Index([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
            ...
            1835, 1836, 1837, 1838, 1839, 1840, 1841, 1842, 1843, 1844],
           dtype='int64', length=1845)


In [299]:
count_vector = CountVectorizer(ngram_range=(1,1))

In [300]:
c_vector1=count_vector.fit_transform(df['카테고리'])
c_vector2=count_vector.fit_transform(df['패턴재질'])
c_vector3=count_vector.fit_transform(df['모양'])
c_vector4=count_vector.fit_transform(df['계절'])
c_vector5=count_vector.fit_transform(df['스타일'])

In [301]:
df.dtypes

상품명      object
카테고리     object
패턴재질     object
모양       object
계절       object
종합점수    float64
스타일      object
dtype: object

In [302]:
genre_c_sim1=cosine_similarity(c_vector1,c_vector1).argsort()[:,::-1]
genre_c_sim2=cosine_similarity(c_vector2,c_vector2).argsort()[:,::-1]
genre_c_sim3=cosine_similarity(c_vector3,c_vector3).argsort()[:,::-1]
genre_c_sim4=cosine_similarity(c_vector4,c_vector4).argsort()[:,::-1]
genre_c_sim5=cosine_similarity(c_vector5,c_vector5).argsort()[:,::-1]

In [303]:
genre_c_sim1

array([[ 922,  984, 1027, ..., 1131, 1132, 1844],
       [ 791, 1122, 1521, ..., 1224, 1225,    0],
       [ 884,  751, 1696, ..., 1203, 1204,    0],
       ...,
       [1526, 1171, 1742, ..., 1213, 1214,    0],
       [1315,   92, 1178, ..., 1213, 1214,    0],
       [1844, 1095, 1117, ..., 1235, 1236,    0]], dtype=int64)

In [304]:
genre_c_sim1.shape, genre_c_sim2.shape, genre_c_sim3.shape, genre_c_sim4.shape, genre_c_sim5.shape

((1845, 1845), (1845, 1845), (1845, 1845), (1845, 1845), (1845, 1845))

In [317]:
def get_recommend_item_list1(df,상품이름,top=1845):
    #특정 영화와 비슷한 영화를추천해야 하기에 '특정 영화' 정보를 추출
    target_item_index=df[df['상품명']==상품이름].index.values
    
    #코사인 유사도 중 비슷한 코사인 유사도를 가진 정보 추출
    sim_index1=genre_c_sim1[target_item_index,:].reshape(-1)
    sim_index2=genre_c_sim2[target_item_index,:].reshape(-1)
    sim_index3=genre_c_sim3[target_item_index,:].reshape(-1)
    sim_index4=genre_c_sim4[target_item_index,:].reshape(-1)
    sim_index5=genre_c_sim5[target_item_index,:].reshape(-1)
    
    #본인 제외
    sim_index1=sim_index1[sim_index1 != target_item_index]
    sim_index2=sim_index2[sim_index2 != target_item_index]
    sim_index3=sim_index3[sim_index3 != target_item_index]
    sim_index4=sim_index4[sim_index4 != target_item_index]
    sim_index5=sim_index5[sim_index5 != target_item_index]
    
    #data frame로 만들고 vote_count로 정렬한뒤 return
    #1 카테고리 2패턴재질 3모양 4계절 5스타일
    #우선순위 계절 카테고리 모양 스타일 패턴재질순
    result1=df.iloc[sim_index1].sort_values('종합점수',ascending=False)[:100]
    result2=df.iloc[sim_index2].sort_values('종합점수',ascending=False)[:100]
    result3=df.iloc[sim_index3].sort_values('종합점수',ascending=False)[:100]
    result4=df.iloc[sim_index4].sort_values('종합점수',ascending=False)[:100]
    result5=df.iloc[sim_index5].sort_values('종합점수',ascending=False)[:100]
    
    result4['항목']=5
    result1['항목']=4
    result3['항목']=3
    result5['항목']=2
    result2['항목']=1
    
    results=pd.concat([result1,result2,result3,result4,result5],ignore_index=True)
    results=results.sort_values('종합점수',ascending=False)[:100]
#     results=results.sort_values(['종합점수','계절','카테고리','모양','스타일','패턴재질'],ascending=False)[:1000]
    results=results.drop_duplicates(['상품명'])
    #5개의 result에서 공통된 값들만 합침
    return results

In [318]:
get_recommend_item_list1(df,'[La belle rose]페이어 유넥티')

상품명   카테고리 패턴재질    모양          계절  종합점수    스타일  \
0                  카라멜 슬림핏 셔츠롱원피스   롱원피스   무지    단추       여름     1.75    페미닌   
1    [La belle rose]데이니 여리핏 브이트임티    티셔츠   무지    유넥      봄 가을    0.31    러블리   
202  [La belle rose]로제 스퀘어 미니훌원피스  미니원피스   무지  스퀘어넥       여름     0.24  심플베이직   
303                  로우 핀턱 퍼프블라우스   블라우스   무지    퍼프       여름     0.17     청순   
304    [La belle rose]프레인 퍼프 스퀘어티    티셔츠   무지  스퀘어넥      봄 여름    0.16    러블리   
305  [La belle rose]달링유 셔링 랩 블라우스   블라우스   무지    셔링       여름     0.13    러블리   
407   [La belle rose]바넷 브이 끈 롱원피스   롱원피스   무지   브이넥      봄 가을    0.11     섹시   
107                    카리나 썸머 볼레로    가디건   무지    트임      봄 여름    0.11    러블리   
308                   에르제 프릴 블라우스   블라우스   무지    프릴       여름     0.09     청순   
109                    로드니 훌 치마바지  미니스커트   무지    밴딩       여름     0.07   모던시크   
210                      디안 큐빅귀걸이    귀걸이   금속    큐빅  봄 여름 가을 겨울  0.07     섹시   
111                기획특가♥웰데이 베이직셔츠  셔츠/남방   무지    언발       가을     0.06    러블리   
313                   에포 쫀쫀 레깅스팬츠   일자바지   무지    일자      봄 여름    0.05  심플베이직   
312    [La belle rose]드로우 셔링 롱원피스   롱원피스   무지    셔링       여름     0.05     청순   
214                   샤이니 새틴 블라우스   블라우스  시스루    카라       겨울     0.04    유니크   
215                   유리안 스퀘어블라우스   블라우스   골지  스퀘어넥       여름     0.03    러블리   
216          로레앙 홀터넥 롱원피스(스트랩set)   롱원피스   무지    밴딩       여름     0.03     청순   
117                   앨리나 프릴 블라우스   블라우스   무지    셔링       여름     0.02    러블리   
320  [La belle rose]베리유 플레어 카라원피스  미니원피스   무지   플레어       겨울     0.02    하객룩   
319                      줄레아 블라우스   블라우스   골지    유넥      봄 가을    0.02     청순   
118                 홀린 린넨 뷔스티에원피스  미니원피스   무지  뷔스티에       여름     0.02  심플베이직   

     항목  
0     4  
1     4  
202   3  
303   5  
304   5  
305   5  
407   2  
107   1  
308   5  
109   1  
210   3  
111   1  
313   5  
312   5  
214   3  
215   3  
216   3  
117   1  
320   5  
319   5  
118   1

In [281]:
target_item_index=df[df['상품명']=='[DAYONE LABEL]누브 보트넥롱원피스'].index.values

In [282]:
target_item_index

array([1216], dtype=int64)

In [289]:
    sim_index1=genre_c_sim1[target_item_index,:100].reshape(-1)
    sim_index2=genre_c_sim2[target_item_index,:30].reshape(-1)
    sim_index3=genre_c_sim3[target_item_index,:30].reshape(-1)
    sim_index4=genre_c_sim4[target_item_index,:30].reshape(-1)
    sim_index5=genre_c_sim5[target_item_index,:30].reshape(-1)

In [288]:
sim_index1

array([ 873,  373, 1672, 1420, 1423, 1028, 1426, 1660, 1429, 1035, 1430,
       1037, 1205, 1204, 1256,  177, 1202,  369,  368,  366, 1048, 1641,
        363,  361,  722,  356, 1215, 1216, 1019,  152], dtype=int64)

In [193]:
sim_index1=sim_index1[sim_index1 != target_item_index]
sim_index2=sim_index2[sim_index2 != target_item_index]
sim_index3=sim_index3[sim_index3 != target_item_index]
sim_index4=sim_index4[sim_index4 != target_item_index]
sim_index5=sim_index5[sim_index5 != target_item_index]

In [204]:
#4 1 3 5 2 순서대로
result1=df.iloc[sim_index1].sort_values('종합점수',ascending=False)[:30]
result2=df.iloc[sim_index2].sort_values('종합점수',ascending=False)[:30]
result3=df.iloc[sim_index3].sort_values('종합점수',ascending=False)[:30]
result4=df.iloc[sim_index4].sort_values('종합점수',ascending=False)[:30]
result5=df.iloc[sim_index5].sort_values('종합점수',ascending=False)[:30]

In [205]:
result4['항목']=5
result1['항목']=4
result3['항목']=3
result5['항목']=2
result2['항목']=1
result1

상품명  카테고리   패턴재질    모양        계절  종합점수    스타일  \
873      [La belle rose]오라라 쉬폰 랩원피스  롱원피스     무지    쉬폰    봄 가을    0.00     청순   
1205               아미르 머메이드 뷔스티에원피스  롱원피스     무지  뷔스티에    봄 가을    0.00    하객룩   
1019                페어린 오픈카라 셔츠롱원피스  롱원피스     무지    카라    봄 가을    0.00     청순   
1215  [DAYONE LABEL/1+1♥]버디 나시 롱원피스  롱원피스     무지    유넥     여름     0.00    러블리   
722                       폴링 쉬폰롱원피스  롱원피스     도트    쉬폰    봄 여름    0.00  심플베이직   
361                 엘리엇 머메이드 나시롱원피스  롱원피스     무지  머메이드    봄 여름    0.00     섹시   
363                     젤스 시스루 롱원피스  롱원피스    시스루  라운드넥     겨울     0.00     섹시   
1641                      앤더 골지롱원피스  롱원피스     골지   브이넥   가을 겨울    0.00  심플베이직   
368                    토플 골지 니트롱원피스  롱원피스     골지   브이넥     겨울     0.00     섹시   
369                  포미 머메이드 나시롱원피스  롱원피스     무지  스퀘어넥    봄 가을    0.00     섹시   
1202                   소안 뷔스티에 롱원피스  롱원피스     무지  뷔스티에  봄 가을 겨울   0.00    하객룩   
1204                   시앤 배색카라 롱원피스  롱원피스     배색    카라     여름     0.00    하객룩   
1256     [La belle rose]로미오 브이 롱원피스  롱원피스     무지   브이넥    봄 가을    0.00    러블리   
1037                     후프 골지브이원피스  롱원피스  스트라이프    골지     겨울     0.00     청순   
1430                 로이스 스퀘어 니트롱원피스  롱원피스     무지  스퀘어넥    봄 가을    0.00     청순   
1035                   헤이글 플라워 롱원피스  롱원피스    플라워  라운드넥    봄 여름    0.00     청순   
1429                    로이 레이스 롱원피스  롱원피스     무지    단추     여름     0.00     청순   
1660                  엘란 머메이드 퍼프원피스  롱원피스     무지  머메이드     여름     0.00    러블리   
1028            하미 셔링 셔츠롱원피스(벨트set)  롱원피스     무지    셔링  봄 여름 가을   0.00     청순   
1423                      로벤 니트롱원피스  롱원피스     무지    트임     가을     0.00    페미닌   
1420                  로로 스퀘어 플라워원피스  롱원피스    플라워  스퀘어넥     여름     0.00     청순   
1672                    오즈 플레어 롱원피스  롱원피스     골지   브이넥     겨울     0.00     청순   
152                      에라 셔링 롱원피스  롱원피스    플라워    셔링   봄 여름     0.00    러블리   
373             하이브 나시 롱원피스(스트랩set)  롱원피스     무지   브이넥     여름    -0.06     섹시   
1426                    로앤느 쉬폰 롱원피스  롱원피스    플라워    쉬폰    봄 여름   -0.08  심플베이직   
177                  지엘 스트랩 뷔스티에원피스  롱원피스     무지  뷔스티에     여름    -0.51    러블리   
356                     아맨다 셔링 롱원피스  롱원피스     무지    셔링   봄 여름    -0.55     섹시   
366                  켄달 머메이드 나시롱원피스  롱원피스     무지  머메이드     여름    -0.69     섹시   
1048        [La belle rose]이든 롱랩원피스  롱원피스     무지   브이넥    봄 여름   -1.71    캐주얼   

      항목  
873    4  
1205   4  
1019   4  
1215   4  
722    4  
361    4  
363    4  
1641   4  
368    4  
369    4  
1202   4  
1204   4  
1256   4  
1037   4  
1430   4  
1035   4  
1429   4  
1660   4  
1028   4  
1423   4  
1420   4  
1672   4  
152    4  
373    4  
1426   4  
177    4  
356    4  
366    4  
1048   4

In [206]:
results=pd.concat([result1,result2,result3,result4,result5],ignore_index=True)
results.sort_values(['종합점수','항목'],ascending=False)[:30]


상품명    카테고리   패턴재질    모양      계절  종합점수    스타일  \
118     [La belle rose]바넷 브이 끈 롱원피스    롱원피스     무지   브이넥  봄 가을    0.11     섹시   
88                   기획특가♥웰데이 베이직셔츠   셔츠/남방     무지    언발   가을     0.06    러블리   
59                      에포 쫀쫀 레깅스팬츠    일자바지     무지    일자  봄 여름    0.05  심플베이직   
89                         줄레아 블라우스    블라우스     골지    유넥  봄 가을    0.02     청순   
90                          디엘 브이니트  니트/스웨터     하찌   브이넥   가을     0.00  심플베이직   
91       [DAYONE LABEL]투핀턱 세미와이드슬랙스     슬랙스     무지   와이드  봄 가을    0.00  심플베이직   
92                       울림 셔링 랩티셔츠     티셔츠     무지     랩  봄 가을    0.00    러블리   
93        [La belle rose]리모 크롭 후드집업      점퍼     무지    크롭  봄 가을    0.00    캐주얼   
94                        샐리 단가라티셔츠     티셔츠  스트라이프  라운드넥   가을     0.00    페미닌   
95                       퍼제 양브이 크롭티     티셔츠     무지    크롭  봄 가을    0.00     청순   
96                         트루디 블라우스    블라우스     무지    카라  봄 가을    0.00     청순   
97                       블라디 플리츠스커트   미니스커트     무지   플리츠   가을     0.00    러블리   
98                      라이키 슬림 일자팬츠    일자바지     데님    슬림  봄 가을    0.00    캐주얼   
99                      르빗 생지 데님스커트   미니스커트     데님   A라인   가을     0.00  심플베이직   
100                    아멜로 플레어 롱원피스    롱원피스     무지    셔링  봄 가을    0.00     청순   
101       [La belle rose]겔러 백리본 배색티     티셔츠     배색    리본  봄 가을    0.00  심플베이직   
102                     모모 슬림핏 롱원피스    롱원피스     무지    슬림  봄 가을    0.00     섹시   
103             로빈 슬림핏 트렌치코트(벨트set)      코트     무지    카라   가을     0.00  심플베이직   
104                     윌리 플레어 롱스커트   롱스커트      무지   플레어  봄 가을    0.00     청순   
105                       이헨 셔링블라우스    블라우스     무지    셔링  봄 가을    0.00     청순   
106                     로밍 여리핏 카라니트  니트/스웨터     무지    카라  봄 가을    0.00  심플베이직   
107  [La belle rose] 로망드 라운드카라 롱원피스    롱원피스     무지    카라  봄 가을    0.00    캐쥬얼   
108                       세컨드 루즈핏자켓      자켓     무지    카라   가을     0.00    하객룩   
109        [DAYONE LABEL]플리에 레이스원피스   미니원피스    레이스  라운드넥  봄 가을    0.00  심플베이직   
110                     러번 세미 부츠컷팬츠     부츠컷     무지   부츠컷  봄 가을    0.00  심플베이직   
111                     러빙미 셔링 블라우스    블라우스     무지    셔링   가을     0.00  심플베이직   
112                 코노 셔츠원피스(벨트set)   미니원피스     무지    카라  봄 가을    0.00     청순   
113                     클레아 핀턱 롱스커트    롱스커트     골지    밴딩  봄 가을    0.00     청순   
114                        달리아 롱스커트    롱스커트     무지   플레어  봄 가을    0.00  심플베이직   
0        [La belle rose]오라라 쉬폰 랩원피스    롱원피스     무지    쉬폰  봄 가을    0.00     청순   

     항목  
118   2  
88    5  
59    3  
89    5  
90    5  
91    5  
92    5  
93    5  
94    5  
95    5  
96    5  
97    5  
98    5  
99    5  
100   5  
101   5  
102   5  
103   5  
104   5  
105   5  
106   5  
107   5  
108   5  
109   5  
110   5  
111   5  
112   5  
113   5  
114   5  
0     4